# fly.toml app configuration file generated for gymille-frontend on 2023-06-24T01:33:41+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "gymille-frontend"
primary_region = "arn"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
