version: '3.8'

services:
  frontend:
    build: ./frontend
    container_name: app-frontend
  backend:
    build: ./backend
    container_name: app-backend
  nginx-reverse-proxy:
    image: nginx:1.24.0-alpine
    container_name: nginx-reverse-proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '5000:5000'
