name: Deploy frontend

on:
  push:
    paths:
      - 'frontend/**'

env:
  FLY_API_TOKEN: ${{ secrets.FRONTEND.FLY_API_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        working-directory: ./frontend
