name: Run Cypress tests

on:
  push:
    paths:
      - 'frontend/**'
      - 'backend/**'
      - '.github/workflows'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: npm run pretest
        working-directory: ./backend

      - run: |
          npm ci
          npm run dev &
        working-directory: ./backend

      - name: Wait for backend to start
        run: sleep 15

      - uses: cypress-io/github-action@v5
        with:
          working-directory: ./frontend
          start: npm run dev
